EPOv2/EPOv2/Controllers/MaintenanceController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web.Mvc;

namespace EPOv2.Controllers
{
    using System;

    using DomainModel.Entities;

    using EPOv2.Business.Interfaces;
    using EPOv2.ViewModels;

    public class MaintenanceController : Controller
    {
        private readonly IData _data;

        private readonly IUserManagement _userManagement;

        private readonly IAd _ad;

        private readonly IMain _main;

        public MaintenanceController(IData data, IUserManagement userManagement, IAd ad, IMain main)
        {
            _data = data;
            _userManagement = userManagement;
            _ad = ad;
            _main = main;
        }
      
        // GET: Maintenance
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ManageEntity()
        {
            //var data = new Data();
            var model = _data.GetEntityViewModelList();
            return View(model);
        }

        [HttpGet]
        public ActionResult EditEntity(int id)
        {
            var model = _data.GetEntityViewModelById(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult EditEntity(EntityViewModel model)
        {
            _data.SaveEntity(model);
            return RedirectToAction("ManageEntity");
        }

        [HttpGet]
        public ActionResult AddEntity()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddEntity(Entity model)
        {
            _data.SaveEntity(model);
            return RedirectToAction("ManageEntity");
        }

        public ActionResult ActivateEntity(int id)
        {
            _data.DeleteOrActivateEntity(id,false);
            return RedirectToAction("ManageEntity");
        }

        public ActionResult DeleteEntity(int id)
        {
            _data.DeleteOrActivateEntity(id);
            return RedirectToAction("ManageEntity");
        }

        #region CostCentre
        public ActionResult ManageCostCentre()
        {
            var model = _data.GetAllCostCentres();
            return View(model);
        }

        public ActionResult CreateCostCentre()
        {
            var model = new CostCentre();
            ViewBag.Action = "Create";
            return View("EditCostCentre", model);
        }

        public ActionResult EditCostCentre(int id)
        {
            var model = _data.GetCostCentre(id);
            ViewBag.Action = "Edit";
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateCostCentre(CostCentre model)
        {
            _data.SaveCostCentre(model);
            return RedirectToAction("ManageCostCentre");
        }

        [HttpPost]
        public ActionResult EditCostCentre(CostCentre model)
        {
            _data.SaveCostCentre(model);
            return RedirectToAction("ManageCostCentre");
        }

        public ActionResult ActivateCostCentre(int id)
        {
            _data.DeleteOrActivateCostCentre(id, false);
            return RedirectToAction("ManageCostCentre");
        }

        public ActionResult DeleteCostCentre(int id)
        {
            _data.DeleteOrActivateCostCentre(id);
            return RedirectToAction("ManageCostCentre");
        }
        #endregion

        #region Cost Centre Owner
        public ActionResult ChangeCostCentreOwner()
        {
            var model = _data.GetCostCentreOwnerVM();
            return View(model);
            // return null;
        }

        [HttpPost]
        public ActionResult ChangeCostCentreOwner(CostCentreOwnerViewModel model)
        {
            var result = _data.SaveCostCentreOwner(model);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult FetchCostCentreOwner(int ccId)
        {
            var result = _data.GetCostCentreOwner(ccId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Account
        public ActionResult ManageAccount()
        {
            var model = _data.GetAccountsAll();
            return View(model.OrderBy(x => x.Type).ThenBy(x => x.Code).ToList());
        }

        public ActionResult CreateAccount()
        {
            var model = new Account();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateAccount(Account model)
        {
            _data.SaveAccount(model);
            return RedirectToAction("ManageAccount");
        }

        public ActionResult EditAccount(int id)
        {
            var model = _data.GetAccount(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult EditAccount(Account model)
        {
            _data.SaveAccount(model);
            return RedirectToAction("ManageAccount");
        }

     
        public ActionResult ActivateAccount(int id)
        {
            _data.DeleteOrActivateAccount(id,false);
            return RedirectToAction("ManageAccount");
        }

       
        public ActionResult DeleteAccount(int id)
        {
            _data.DeleteOrActivateAccount(id);
            return RedirectToAction("ManageAccount");
        }

        #endregion

        #region Mapping Account to Cost Centre

        public ActionResult MapAccountToCC()
        {
            var model = _data.GetCostCentresDDLVM(); 
            return View(model);
        }

        public ActionResult FetchAccountCCMap(int ccId)
        {
            var model = _data.GetAccountToCCViewModelList(ccId);
            return PartialView("_AccountToCCMap",model);
        }

        public ActionResult DeleteAccountCCMap(int ccId, int id)
        {
            _data.DeleteOrActivateAccountToCCMap(id, true);
            var model = _data.GetAccountToCCViewModelList(ccId);
            return PartialView("_AccountToCCMap", model);
        }

        public ActionResult ActivateAccountCCMap(int ccId, int id)
        {
            _data.DeleteOrActivateAccountToCCMap(id, false);
            var model = _data.GetAccountToCCViewModelList(ccId);
            return PartialView("_AccountToCCMap", model);
        }

        [HttpGet]
        public ActionResult AddAccToCCMapMapping()
        {
            var model = _data.GetCostCentresDDLVM();
            return View(model);
        }

        public ActionResult FetchAccountListForMap(int ccId, int type)
        {
            var model = _data.GetAccountVMFilteredList(ccId, type);
            return PartialView("_AccountListForMap", model);
        }

        [HttpPost]
        public ActionResult AddAccToCCMapMapping(AccountToCostCentreAdding model)
        {
            _data.SaveAccountToCCMapping(model);
            return RedirectToAction("MapAccountToCC");
        }

        #endregion

        #region Mapping Account to Category

        public ActionResult ManageAccountCategory()
        {
            var model = _data.GetAccountCategoryList();
            return View("ManageCategory",model);
        }

        [HttpGet]
        public ActionResult AccountCategoryCreate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AccountCategoryCreate(AccountCategory model)
        {
            _data.SaveAccountCategory(model);
            return RedirectToAction("ManageAccountCategory");
        }

        public ActionResult ActivateAccountCategory(int id)
        {
            _data.DeleteOrActivateAccountCategory(id, false);
            return RedirectToAction("ManageAccountCategory");
        }

        public ActionResult DeleteAccountCategory(int id)
        {
            _data.DeleteOrActivateAccountCategory(id);
            return RedirectToAction("ManageAccountCategory");
        }

        public ActionResult EditAccountCategory(int id)
        {
            var model = _data.GetAccountCategory(id);
            return View(model);
        }
        public ActionResult EditAccountCategory(AccountCategory model)
        {
            _data.SaveAccountCategory(model);
            return RedirectToAction("ManageAccountCategory");
        }
        [HttpGet]
        public ActionResult AddAccountCategoryMapping()
        {
            var model = _data.GetAccountCategoryDDL();
            return View(model);
        }

        public ActionResult FetchAccountsListForCategoryMap(int categoryId)
        {
            var model = _data.GetAccountToCategoryAddingViewModel(categoryId);
            return PartialView("_AccountListForCategoryMap",model );
        }

        [HttpGet]
        public ActionResult MapAccountToCategory()
        {
            var list = _data.GetAccountToCategoryMappingList();
            return View(list);
        }

        [HttpPost]
        public ActionResult AddAccountCategoryMapping(AccountToCategoryAdding model)
        {
            _data.SaveAccountToCategoryMap(model);
            return RedirectToAction("MapAccountToCategory");
        }

        public ActionResult ActivateAccountToCategory(int id)
        {
            _data.DeleteOrActivateAccountToCategory(id, false);
            return RedirectToAction("MapAccountToCategory");
        }

        public ActionResult DeleteAccountToCategory(int id)
        {
            _data.DeleteOrActivateAccountToCategory(id);
            return RedirectToAction("MapAccountToCategory");
        }

        #endregion

        #region Entity to Cost Centre mapping

        public ActionResult MapEntityToCC()
        {
            var model = _data.GetEntityDDLVM();
            return View(model);
        }

        public ActionResult FetchCCEntityMap(int entityId)
        {
            var model = _data.GetCostCentreToEntityViewModelList(entityId);
            return PartialView("_CCToEntityMap", model);
        }

        public ActionResult DeleteCCEntityMap(int entityId, int id)
        {

EPOv2/EPOv2/Views/Maintenance/AddAccountCategoryMapping.cshtml
@model EPOv2.ViewModels.AccountCategoryDLLViewModel
@{
    ViewBag.Title = "Add Account to Category Mapping";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script type="text/javascript">

    function selectCategory(object) {
        var categoryID = object.value;
        if (categoryID != null && categoryID !== '') {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("FetchAccountsListForCategoryMap")',
                cache: false,
                data: {
                    categoryId: categoryID
                },
                error: function (xhr, status, error) {
                    $(".alert").html(xhr.responseText);
                },
                success: function (result) {
                    $('#ccList').html(result);
                }
            });
        }
    }

 
</script>

<h3>Add new Account to Category mapping</h3>
@using (Html.BeginForm())
{
    <div>
        <div class="col-md-3">
            @Html.DropDownListFor(m => m.SelectedCategory, new SelectList(Model.AccountCategories, "Id", "Name"), "Select Category", new { @class = "form-control input-sm input", onchange = "selectCategory(this)" })
        </div>
        <div id="ccList" class="col-md-5"></div>
        <div class="col-md-3">
            <input type="submit" value="Save" class="btn btn-success btn-sm" />
            <button href="#" class="btn btn-default btn-sm" role="button" onclick="window.location.href='@Url.Action("MapAccountToCategory", "Maintenance")'">Back</button>
        </div>
    </div>
}

EPOv2/EPOv2/Views/Maintenance/CapexApproverEdit.cshtml
@model EPOv2.ViewModels.CapexApproverCRUDViewModel

@{
    ViewBag.Title = "CapexApproverEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Capex Approver Edit</h2>

@using (Html.BeginForm("CapexApproverEdit","Maintenance", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Limit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Limit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Limit, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("User", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedUser, new SelectList(Model.Users, "Id", "FullName"), "Select User", new { @class = "form-control input-sm input" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Division", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedDivision, new SelectList(Model.Divisions, "Id", "FullName"), "Select Division", new { @class = "form-control input-sm input" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CapexApprovers")
</div>

EPOv2/EPOv2/Views/Maintenance/ChangeOrderAuthor.cshtml
@model EPOv2.ViewModels.OrderViewModel
@{
    ViewBag.Title = "Change Order Author";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">

    function searchOrder() {
        var tNumber = $("#OrderNumber").val();
        if (tNumber !== "") {
            $('#EPOloading1').removeClass('hidden');
            $.ajax({
                type: 'GET',
                url: '@Url.Action("FetchOrderForChangeAuthor")',
            cache: false,
            data: {
                OrderNumber: tNumber
            },
            error: function (xhr, status, error) {
                $(".alert").html(xhr.responseText);
                $('#div-reassignOrderForm').empty();
                $('#EPOloading1').addClass('hidden');
            },
            success: function (result) {
                $('#EPOloading1').addClass('hidden');
                $('#div-reassignOrderForm').empty();
                $('#div-reassignOrderForm').html(result);
            }
        });}
    }

        function submitForm() {
            bootbox.confirm("Are you sure?", function (result) {
                if (result === true) {
                    var $form = $('form[id="OrderAuthorChange"]');
                  $.ajax({
                        type: 'POST',
                        url: '@Url.Action("OrderAuthorChange")',
                        data: $form.serialize(),
                        cache: false,
                        error: function (xhr, status, error) {
                            $('#ErrorAlert').show(400).fadeIn().delay(2500).hide(600).fadeOut();
                        },
                        success: function (result) {
                            $('#SaveAlert').show(500).fadeIn().delay(1000).hide(500).fadeOut();
                        }
                    });
                }
            });
        }

    function SelectAuthor(object) {
        if(object.value!==0 && object.value!=='' && object.value!==null){
            $('#btn-changeStatus').removeAttr("disabled");
        }
        else $('#btn-changeStatus').attr("disabled", "disabled");
    }
</script>
<br />
<div class="row">
    <div class="col-md-12">
        <div id="div-reassignOrderForm">
            <div class="col-md-6">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <span class="panel-title">Change Order Author</span>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-3">Order #</div>
                            <div class="col-md-3">
                                @Html.TextBoxFor(m => Model.OrderNumber, null, new { @class = "form-control input-sm input", @onkeypress = "return isNumberKey(event)" })
                            </div>
                            <div class="col-md-1">
                                <button type="button" class="btn btn-default btn-sm" onclick="searchOrder()">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div id="SaveAlert" class="alert alert-success" style="display: none;">Saved Successfully</div>
    </div>
    <div class="col-md-12">
        <div id="ErrorAlert" class="alert alert-danger" style="display: none;">Error! </div>
    </div>
    <div class="row">
        <div class="col-sm-12 text-center hidden" id="EPOloading1">
            <div class="spinner spinner-info"></div>
        </div>
    </div>
</div>

EPOv2/EPOv2/Views/Maintenance/Divisions.cshtml
@model IEnumerable<DomainModel.Entities.Division>
@{
    ViewBag.Title = "Divisions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Divisions</h2>
<p>
    @Html.ActionLink("Create New", "DivisionCreate")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CostCentreRangeFrom)
        </th>
        <th>
                @Html.DisplayNameFor(model => model.CostCentreRangeTo)
            </th>
        <th>
                @Html.DisplayNameFor(model => model.Owner)
            </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostCentreRangeFrom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostCentreRangeTo)
            </td>
            <td>
                @item.Owner.UserInfo.FirstName @item.Owner.UserInfo.LastName
            </td>
            <td>
                <a href="@Url.Action("DivisionEdit", "Maintenance", new {id=item.Id})" class="btn btn-success control-btn-crud">
                    <span class="glyphicon glyphicon-edit"></span>
                </a>
            </td>
        </tr>
    }

</table>

EPOv2/EPOv2/Views/Maintenance/EditAccount.cshtml
@model DomainModel.Entities.Account

@{
    ViewBag.Title = "EditAccount";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(function () {
      //  $("[name='IsDeleted']").bootstrapSwitch();

    });
</script>
<h2>Edit Account</h2><hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
   
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeleted)
                    @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                </div>

            </div>
        </div>*@



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ManageAccount")
</div>

EPOv2/EPOv2/Views/Maintenance/ManageEntity.cshtml
@using EPOv2.ViewModels
@model IEnumerable<EPOv2.ViewModels.EntityViewModel>

@{
    ViewBag.Title = "ManageEntity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ManageEntity</h2>

<p>
    @Html.ActionLink("Add New", "AddEntity")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodeNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prefix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ACN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ABN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fax)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isDelete)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastModifiedBy)
        </th>
        <th></th>
    </tr>

    @foreach (EntityViewModel item in Model)
    {
        <tr>
            <td>
                @Html.HiddenFor(modelItem => item.Id)
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodeNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prefix)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ACN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ABN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fax)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isDelete)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastModifiedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastModifiedBy)
            </td>
            <td>
                    <a href="@Url.Action("EditEntity", "Maintenance", new { id = item.Id })" class="btn btn-success control-btn-crud">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                    <a href="@Url.Action("DeleteEntity", "Maintenance", new { id = item.Id })" class="btn btn-danger control-btn-crud">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                    <a href="@Url.Action("ActivateEntity", "Maintenance", new { id = item.Id })" class="btn btn-info control-btn-crud">
                        <span class="glyphicon glyphicon-repeat"></span>
                    </a>
              
            </td>
        </tr>
    }

</table>

EPOv2/EPOv2/Views/Maintenance/ManageReceiptGroups.cshtml
@model IEnumerable<DomainModel.Entities.Group>

@{
    ViewBag.Title = "Manage Receipt Groups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Manage Receipt Groups</h2>

<p>
    @Html.ActionLink("Create New", "CreateReceiptGroup")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastModifiedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastModifiedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastModifiedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsDeleted)
        </td>
        <td>
            <a href="@Url.Action("EditReceiptGroup", "Maintenance", new {id=item.Id})" class="btn btn-success control-btn-crud">
                <span class="glyphicon glyphicon-edit"></span>
            </a>
            <a href="@Url.Action("DeleteReceiptGroup", "Maintenance", new { id = item.Id })" class="btn btn-danger control-btn-crud">
                <span class="glyphicon glyphicon-trash"></span>
            </a>
            <a href="@Url.Action("ActivateReceiptGroup", "Maintenance", new { id = item.Id })" class="btn btn-info control-btn-crud">
                <span class="glyphicon glyphicon-repeat"></span>
            </a>
        </td>
    </tr>
}

</table>

EPOv2/EPOv2/Views/Maintenance/ManageVoucherStatuses.cshtml
@model IEnumerable<DomainModel.Entities.VoucherStatus>

@{
    ViewBag.Title = "ManageVoucherStatuses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ManageVoucherStatuses</h2>

<p>
    @Html.ActionLink("Create New", "VoucherStatusCreate")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastModifiedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </th>
      
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastModifiedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastModifiedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsDeleted)
        </td>
        
        <td>
            <a href="@Url.Action("EditVoucherStatus", "Maintenance", new { id = item.Id })" class="btn btn-success control-btn-crud">
                <span class="glyphicon glyphicon-edit"></span>
            </a>
            <a href="@Url.Action("DeleteVoucherStatus", "Maintenance", new { id = item.Id })" class="btn btn-danger control-btn-crud">
                <span class="glyphicon glyphicon-trash"></span>
            </a>
            <a href="@Url.Action("ActivateVoucherStatus", "Maintenance", new { id = item.Id })" class="btn btn-info control-btn-crud">
                <span class="glyphicon glyphicon-repeat"></span>
            </a>
        </td>
    </tr>
}

</table>

EPOv2/EPOv2/Views/Maintenance/_AccountListForCategoryMap.cshtml
@model EPOv2.ViewModels.AccountToCategoryAdding


@Html.ListBoxFor(x => Model.SelectedAccounts, new MultiSelectList(Model.Accounts, "Id", "FullName"), new { @class = "form-control input-sm", size=30 })