EPOv2/EPOv2/Controllers/StagingController.cs
using System.Web.Mvc;

namespace EPOv2.Controllers
{
    public class StagingController : Controller
    {

        ////private readonly PurchaseOrderContext _db = new PurchaseOrderContext();
        //private readonly PurchaseOrderOldContext db = new PurchaseOrderOldContext();

        //private readonly Routing _routing = new Routing();
        ////
        //// GET: /Staging/
        //public  ActionResult Index()
        //{
        //    return View();
        //}

        //public async Task<ActionResult> LevelReport()
        //{
        //    var levelLst = await this.db.tblStagingLevels.ToListAsync();
        //    return View(levelLst);
        //}

        //public async Task<ActionResult> EmployeeLevelReport()
        //{
        //    var empLst =await this.db.tblStagingEmployeesDEVs.Where(x => x.isDeleted == 0).ToListAsync();
        //    return View(empLst);
        //}

        //public async Task<ActionResult> CCOwnerReport()
        //{
        //    var ccOwnerLst =await this.db.tblStagingCostCentresDEVs.OrderBy(x=>x.CostCentreCode).ToListAsync();
        //    return View(ccOwnerLst);
        //}

        //public async Task<ActionResult> CCAccountReport(string CostCenteCode)
        //{
        //    ViewBag.ccLst = _routing.GetCostCentreList();
        //    if (CostCenteCode != null)
        //    {
        //        var ccCode = Convert.ToInt32(CostCenteCode);
        //        var ccAccLst =
        //            await this.db.tblStagingAccCCs.Where(x => x.tblStagingCostCentresDEV.CostCentreCode == ccCode).OrderBy(x=>x.AccountCode).ToListAsync();
        //        return View(ccAccLst);
        //    }
        //    return View();
        //}
    }
}

EPOv2/EPOv2/Views/Staging/CCAccountReport.cshtml
@*@model IEnumerable<DomainModel.Entities.tblStagingAccCC>

@{
    ViewBag.Title = "Cost Centre Account Report";
}

<h2>Cost Centre Account Report</h2>
@using (@Html.BeginForm())
{
    <div class="form-group">
        <div class="form-group">
            @Html.Label("Cost Centre: ", new {@class = "control-label col-md-2"})
            <div class="col-md-6">
                @Html.DropDownList("CostCenteCode", (SelectList) ViewBag.CCLst, "Select Cost Centre", new {@class = "form-control", @onchange = "this.form.submit();"})

            </div>
        </div>
    </div>


    if (Model != null)
    {
        <br/>
     <br/>
    <div class="col-md-6">
    <table class="table  table-striped table-condensed ">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.AccountCode)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Updated)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.AccountCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
               
                <td>
                    @Html.DisplayFor(modelItem => item.Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Updated)
                </td>
                
            </tr>
        }

    </table>
            </div>
    }
}*@

EPOv2/EPOv2/Views/Staging/CCOwnerReport.cshtml
@*@model IEnumerable<DomainModel.Entities.tblStagingCostCentresDEV>

@{
    ViewBag.Title = "Cost Centre Owner Report";
}

<h2>Cost Centre Owner Report</h2>
<div class="col-md-7">
    <table class="table table-striped table-condensed ">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.tblEntity.EntityID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CostCentreCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Owner)
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.tblEntity.EntityID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CostCentreCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Owner)
                </td>

            </tr>
        }

    </table>
    @Html.ActionLink("back to Staging reports", "Index")
    </div>*@

EPOv2/EPOv2/Views/Staging/EmployeeLevelReport.cshtml
@*@model IEnumerable<DomainModel.Entities.tblStagingEmployeesDEV>

@{
    ViewBag.Title = "EmployeeLevelReport";
}

<h2>EmployeeLevelReport</h2>
<div class="col-md-7">
    <table class="table table-striped table-condensed ">
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.Employee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tblStagingLevel.level)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manager)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isDeleted)
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Employee)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblStagingLevel.level)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Manager)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.isDeleted)
                </td>

            </tr>
        }

    </table>
    @Html.ActionLink("back to Staging reports", "Index")
</div>*@

EPOv2/EPOv2/Views/Staging/Index.cshtml
@*@model DomainModel.Entities.PurchaseOrderContext
@{
    ViewBag.Title = "Staging Reports";
}

<h2>Staging Reports</h2>

<li>@Html.ActionLink("Level report", "LevelReport", "Staging")</li>
<li>@Html.ActionLink("Employee Level report", "EmployeeLevelReport", "Staging")</li>
<li>@Html.ActionLink("Cost Centre Owner", "CCOwnerReport", "Staging")</li>
<li>@Html.ActionLink("CC/Account", "CCAccountReport", "Staging")</li>*@

EPOv2/EPOv2/Views/Staging/LevelReport.cshtml
@*@model IEnumerable<DomainModel.Entities.tblStagingLevel>

@{
    ViewBag.Title = "Level Report";
}

<h2>Level Report</h2>
<div class="col-md-6">
    <table class="table table-striped table-condensed ">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.level)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.limit)
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.level)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.limit)
                </td>

            </tr>
        }

    </table>
@Html.ActionLink("back to Staging reports", "Index")
   </div>*@
    