EPOv2/EPOv2/Controllers/CapexController.cs
using System.Web.Mvc;

namespace EPOv2.Controllers
{
    using System;
    using System.IO;

    using EPOv2.Business;
    using EPOv2.Business.Interfaces;
    using EPOv2.Migrations;
    using EPOv2.ViewModels;

    public class CapexController : Controller
    {
        private readonly IData _data;

        private readonly IUserInterface _userInterface;

        private readonly IMain _main;

        private readonly IRouting _routing;

        private readonly IOutput _output;

        public CapexController(IData data, IUserInterface userInterface, IMain main, IRouting routing, IOutput output)
        {
            this._data = data;
            this._userInterface = userInterface;
            this._main = main;
            this._routing = routing;
            this._output = output;
        }

        public ActionResult Dashboard()
        {
            return this.View();
        }

        // GET: Capex
        public ActionResult Create()
        {
            ViewBag.Title = "new Capex";
            var model = _data.GetCapexCRUDViewModel();  // new CapexCRUDViewModel() {CapexCompanyBox = new CapexCompanyBox(), CapexDetailBox = new CapexDetailBox()};
            return View(model);
        }

        [HttpPost]
        public ActionResult SaveCapex(CapexCRUDViewModel model, string button)
        {
            if (button == "Save")
            {
                try
                {
                    var capex= _main.SaveCapex(model);
                    _main.DeleteExistingCapexRouting(capex);
                    _main.StartRouting(capex);
                    _main.SendCapexApproveNotification(capex.Id,this);
                    _main.SendCapexNotificationToAuthor(model.Id, this);
                }
                catch (Exception e)
                {
                    _main.LogError("CapexController.SaveCapex",e);
                }
            }
            return RedirectToAction("Dashboard");
        }

        public ActionResult FetchCostCentre(int entityId)
        {
            var model = _data.GetCapexCompanyBox(entityId);
            return this.PartialView("_CompanyBox", model);

        }

        public ActionResult OrdersForMyCapex()
        {

            return null;
        }

        public ActionResult DashboardCapexForApprove()
        {
            var list = _userInterface.GetCapexesForApprove();
            ViewBag.Action = "Approve";
            return this.PartialView("_DashboardCapexesShort", list);
        }

        public ActionResult DashboardMyCapexes()
        {
            var list = _userInterface.GetMyCapexes();
            ViewBag.Action = "Edit";
            ViewBag.Action2 = "View";
            return this.PartialView("_DashboardCapexes",list);
        }

        public ActionResult ShowTransactions(int capexId)
        {
            return this.PartialView("_Transactions", _main.GetCapexTransactions(capexId));
        }

        
        public ActionResult ApproveCapex(DashboardViewModel model)
        {
            var capexVM = _data.GetCapexCRUDViewModel(model.SelectedItem, CapexAction.Authorise);
            ViewBag.Title = "Authorise Capex";
            ViewBag.Action = "Authorise";
            if (capexVM.IsDeleted) return View("DeletedCapex");
            return View("Create", capexVM);
        }

        public ActionResult ApproveCapexExternal(int id)
        {
            return RedirectToAction("ApproveCapex", new DashboardViewModel() { SelectedItem = id });
            //return ApproveCapex(new DashboardViewModel() { SelectedItem = id });
        }

       public ActionResult AuthoriseCapex(CapexCRUDViewModel model, string button)
        {
            _routing.ApproveCapex(model);
            _main.SendCapexApproveNotification(model.Id, this);
            _main.SendCapexNotificationToAuthor(model.Id, this);
            return RedirectToAction("Dashboard");
        }

        [HttpPost]
        public ActionResult DeclineCapex(CapexCRUDViewModel model, string button)
        {
            _routing.DeclineCapex(model);
            _main.SendCapexNotificationToAuthor(model.Id, this);
            return RedirectToAction("Dashboard");
        }

        public ActionResult EditCapex(DashboardViewModel model)
        {
          
            var capexVM = _data.GetCapexCRUDViewModel(model.SelectedItem, CapexAction.Edit);
            ViewBag.Title = "Edit Capex";
            ViewBag.Action = "Edit";
            return View("Create", capexVM);
        }

        public ActionResult ViewCapex(DashboardViewModel model)
        {
           
            ViewBag.Title = "view Capex";
            var capex = _data.GetCapexCRUDViewModel(model.SelectedItem, CapexAction.View);
            return View("Create",capex);
        }
        public ActionResult DeleteCapex(DashboardViewModel model)
        {
            _main.DeleteCapex(model.SelectedItem);
            return RedirectToAction("Dashboard");
        }

        public ActionResult SendNotification(DashboardViewModel model)
        {
            _main.SendCapexApproveNotification(model.SelectedItem,this);
            return RedirectToAction("Dashboard");
        }

        //public ActionResult SendNotification(int id)
        //{
        //    _main.SendCapexApproveNotification(id, this);
        //    return RedirectToAction("Dashboard");
        //}

        [HttpPost]
        public ActionResult ViewDocument(string Id)
        {
           if (!string.IsNullOrEmpty(Id))
            {
                var capexReference = _data.GetCapexReference(Id);
                var fileStream = new FileStream(capexReference,
                                         FileMode.Open,
                                         FileAccess.Read
                                       );
                var fsResult = new FileStreamResult(fileStream, "application/pdf");
                return fsResult;
            }
            return null;
        }

        public ActionResult SearchCapex(SearchViewModel model)
        {
            var result = this._main.SearchCapex(model);
            return this.PartialView("_SearchCapexResult", result);
        }

    }
}

EPOv2/EPOv2/Controllers/ReportController.cs
using System.Net.Mail;
using System.Web.Mvc;
using Hangfire;

namespace EPOv2.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Runtime.Serialization.Json;
    using System.Threading.Tasks;
    using System.Web.Script.Serialization;

    using DomainModel.Entities;

    using EPOv2.Business.Interfaces;
    using EPOv2.Properties;
    using EPOv2.ViewModels;

    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;

    using Serilog;

    public class ReportController : Controller
    {
        private readonly ILogger _logger = Log.Logger;
        private readonly IData _data;

        private readonly IUserManagement _userManagement;

        private readonly IOutput _output;

        private readonly IMain _main;

        private readonly IRouting _routing;

        public ReportController(IData data, IUserManagement userManagement, IOutput output, IMain main,IRouting routing)
        {
            this._data = data;
            this._userManagement = userManagement;
            this._output = output;
            this._main = main;
            this._routing = routing;
        }

        // GET: Report
        public ActionResult Index()
        {
          
              
            return View();
        }

        public ActionResult LevelReport()
        {
            var model = this._data.GetLevels();
            return View(model);
        }

        public ActionResult RoutingReport()
        {
            //var model = Data.GetRoutingTree();
            var model = this._data.GetCostCentresDDLVM(); 
            return this.View(model);
        }

        public ActionResult FetchRoutingStructureForCC(int ccId)
        {
            _logger.Information("Fetch Routing Structure For CC:{ccId}",ccId);
           var model= _routing.GetRoutingStructureForCC(ccId);
            return this.PartialView("_reportingStructureForCC",model);
        }

        public ActionResult AdUsersWithoutPhone()
        {
            var model = _userManagement.GetAllUsersWithoutPhone();
            return this.View(model);
        }

        public ActionResult CostCentreOwnerReport()
        {
            var model = this._data.GetCostCentresWithOwnerVM();
            return this.View(model);
        }

        public ActionResult AdminStats()
        {
            var model = this._data.GetAdminStats();
            return this.View(model);
        }

        public ActionResult RunEttacherEmailReports()
        {
            this.AuthorisedVouchersEmailReport();
            this.DeclinedVouchersEmailReport();
            return View("Index");
        }

        public ActionResult RunOutstandingInvoiceEmailReport()
        {
            this.OutstandingInvoiceEmailReport();
            return this.View("Index");
        }

        public ActionResult RunCostCentreOwnerCheckReport()
        {
            var model = this._data.CheckCostCentreOwners();
            var recipient = Settings.Default.EmptyCcOwnerRecipient;
            if (model.Count > 0)
            {
                this._main.GenerateAndSendCCOwnerReport(this, "_EmptyCostCentreOwnerReport", model, recipient);
            }
            return this.View("Index");
        }

        public void OutstandingInvoiceEmailReport()
        {
            var model = _main.GetOutstandingInvoices();
            _main.GenerateAndSendOutstandingInvoiceReport(this, "_OutstandingInvoiceReport", model);
            //var bodytext = RenderPartialViewToString(this, "OutstandingInvoiceReport", model);
            //var text = PreMailer.MoveCssInline(bodytext).Html;
            //_output.SendEmailReport(text, model);
            //return;
        }

        public void AuthorisedVouchersEmailReport()
        {
            var searchModel = new SearchViewModel { SelectedStatus = 2, DateFrom = DateTime.Today.AddDays(-90).ToString("dd/MM/yyyy"), DateTo = DateTime.Today.ToString("dd/MM/yyyy") }; //2 - Authorised
            var model = _main.SearchVoucher(searchModel);
            model = this._main.GetAuthorisedVouchersReport(model);
            var bodytext = RenderPartialViewToString(this, "EttacherReportAuthorised", model.OrderByDescending(x => x.AuthorisationDate));
            _output.SendEmailForEttacher(bodytext, "Authorised vouchers");
            // BackgroundJob.Enqueue(() => BackgroundAuthoriseVoucherEmail());
        }

        public void DeclinedVouchersEmailReport()
        {
            var searchModel = new SearchViewModel { SelectedStatus = 4, DateTo = DateTime.Today.ToString("dd/MM/yyyy") }; //4 - Declined
            var model = _main.SearchVoucher(searchModel);
            var bodytext = RenderPartialViewToString(this, "EttacherReportAuthorised", model.OrderByDescending(x => x.Date));
            _output.SendEmailForEttacher(bodytext, "Declined vouchers");
            // BackgroundJob.Enqueue(() => BackgroundDeclineVoucherEmail());
        }

        public void BackgroundDeclineVoucherEmail()
        {
            var searchModel = new SearchViewModel { SelectedStatus = 4, DateTo = DateTime.Today.ToString("dd/MM/yyyy") }; //4 - Declined
            var model = _main.SearchVoucher(searchModel);
            var bodytext = RenderPartialViewToString(this, "EttacherReportAuthorised", model.OrderByDescending(x => x.Date));
            _output.SendEmailForEttacher(bodytext, "Declined vouchers");
        }
        //This task will run in background using Hangfire.Because it's timeout problem with old code.
        public void BackgroundAuthoriseVoucherEmail()
        {
            var searchModel = new SearchViewModel { SelectedStatus = 2, DateFrom = DateTime.Today.AddDays(-90).ToString("dd/MM/yyyy"), DateTo = DateTime.Today.ToString("dd/MM/yyyy") }; //2 - Authorised
            var model = _main.SearchVoucher(searchModel);
            model = this._main.GetAuthorisedVouchersReport(model);
            var bodytext = RenderPartialViewToString(this, "EttacherReportAuthorised", model.OrderByDescending(x => x.AuthorisationDate));
            _output.SendEmailForEttacher(bodytext, "Authorised vouchers");
        }

        public ActionResult AuthorisedVouchersEmailReportTest()
        {
            var searchModel = new SearchViewModel { SelectedStatus = 2 };//4 - Declined
            var model = _main.SearchVoucher(searchModel);
            return this.View("EttacherReportAuthorised",model);
        }

        public static string RenderPartialViewToString <T>(Controller controller, string viewName, T model)
        {
            controller.ViewData.Model = model;
            using (StringWriter sw = new StringWriter())
            {
                ViewEngineResult viewResult = ViewEngines.Engines.FindView(controller.ControllerContext, viewName,null);
                ViewContext viewContext = new ViewContext(controller.ControllerContext, viewResult.View, controller.ViewData, controller.TempData, sw);
                viewResult.View.Render(viewContext, sw);
                return sw.ToString();
            }
        }

        [HttpGet]
        public ActionResult PurchaseOrderAccurals()
        {
            var filterModel = this._data.GetReportEPOAccuralsFilterViewModel();
            return this.View("EPOAccural",filterModel);
        }

        [HttpPost]
        public ActionResult PurchaseOrderAccurals(ReportEPOAccuralsFilterViewModel filter)
        {
            var model = this._data.RunEPOAccuralsReport(filter);
            return this.PartialView("_epoAccuralResult", model);
        }


        public ActionResult UnreceiptedPO()
        {
            var model = _data.GetUnrecieptedPO(DateTime.Today);
            return View(model);
        }

        #region Budget

        public ActionResult Budget()
        {
            var model = this._data.GetBudgetReportEntryDataViewModel();
            return this.View(model);
        }

        public ActionResult FetchBudgetReportEntryData(int entityId)
        {
            _logger.Information($"Fetch Budget Entry data for entity:{entityId}");
            var model = _data.GetBudgetReportEntryDataViewModel(entityId);
            return PartialView("_BudgetReportFilter", model);
        }

        public ActionResult RunBudgetReport(BudgetReportEntryDataViewModel filter)
        {
            _logger.Information("Run Budget Report for Entity:{entityId}, CC:{ccId}, Category:{categoryId}", filter.SelectedEntity,filter.SelectedCostCenter, filter.SelectedCategory);
            var model = _data.GetBudgetReport(filter);
            return PartialView("_BudgetReportResult",model);
        }

        
        public ActionResult GetReForecastAndVarianceForBudgetReport()
        {
            Stream req = Request.InputStream;
            req.Seek(0, System.IO.SeekOrigin.Begin);
            string json = new StreamReader(req).ReadToEnd();

            BudgetReportResult input;
            try
            {
                input = JsonConvert.DeserializeObject<BudgetReportResult>(json);
            }

            catch (Exception e)
            {
                _logger.Error(e, "JsonConvert to BudgetReportResult");
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            _logger.Information($"GetReForecastAndVarianceForBudgetReport");
            var result = _data.GetReForecastAndVarianceForBudgetReport(input);
            return PartialView("_BudgetReportReForecastVariance", result);
        }

        public ActionResult GetDetailsForBudgetReport(string glCode, int period, int entity, int cc,bool isEstimate)
        {
            var model = _data.GetPeriodEPODetailsForBudgetReport(glCode, period, entity, cc, isEstimate);
            return PartialView("_BudgetReportDetails",model);
        }

        public ActionResult GetVoucherDetailsForBudgetReportByCategory(int categoryId, int period, int entity, int cc)
        {

EPOv2/EPOv2/Views/Shared/PdfContainer.cshtml
@model EPOv2.ViewModels.pdfPOContainerViewModel
@{
    ViewBag.Title = "PdfContainer";
    Layout = "~/Views/Shared/_PdfLayout.cshtml";
}
<div id="pdf-container">
    @foreach (var page in Model.PdfPOPages)
    {
        
            Html.RenderPartial("_pdfReport", page);
        <p class="breakhere"></p>
    }
</div>

EPOv2/EPOv2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="epo system" />
        <title>@ViewBag.Title - EPOv2</title>
        @Styles.Render("~/Content/css")
        @*<link rel="stylesheet" href="http://localhost/EPOv2/Content/Site.css" />
        <link rel="stylesheet" href="http://localhost/EPOv2/Content/bootstrap.css" />*@
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/bootstrap")
        <link rel="icon" href="~/content/logos/epologo144.png" type="image/png">
        <link rel="icon" href="~/content/logos/epologov2.png" type="image/png">
      
        <link href="~/Content/jquery.datetimeentry.css" rel="stylesheet" />
        <script src="~/Scripts/jquery.plugin.js"></script>
        <script src="~/Scripts/jquery.mousewheel.js"></script>
        <script src="~/Scripts/jquery.datetimeentry.js"></script>
</head>
    <body>
      
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("EPOv2", "Index", "Home", null, new {@class = "navbar-brand"})
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                      <li class="dropdown">
                            @Html.ActionLink("Orders", null, null, null, new { @class = "dropdown-toggle", data_toggle = "dropdown" })
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Raise new PO", "RaiseNew", "PurchaseOrder")</li>
                                <li>@Html.ActionLink("Budget report", "Budget", "Report")</li>
                            </ul>
                        </li>
                        <li>
                            @Html.ActionLink("Ettacher", null, null, null, new { @class = "dropdown-toggle", data_toggle = "dropdown" })
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Ettacher", "Index", "Ettacher")</li>
                            </ul>
                        </li>

                        @*<li>
                            <a href="@Url.Action("Dashboard", "Capex")">Capex<span class="badge badge-navigation-notification pink">9+</span></a>
                            
                        </li>*@
                        <li>
                            @Html.ActionLink("Tools", null, null, null, new { @class = "dropdown-toggle", data_toggle = "dropdown" })
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Substitution", "ManageSubstitute", "Maintenance")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Re-Submit voucher", "ResubmitVoucher", "Ettacher")</li>
                                <li>@Html.ActionLink("Delete voucher", "DeleteVoucher", "Ettacher")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Report: EPO Accrual", "PurchaseOrderAccurals", "Report")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Modify DueDate", "ModifyDueDate", "PurchaseOrder")</li>

                            </ul>
                        </li>
                        <li>
                            <a href="@Url.Action("Dashboard", "Capex")">Capex <span class="label label-danger hidden"></span></a>
                        </li>
                        <li>
                            @Html.ActionLink(" ","Search", "Home", null, new { @class = "glyphicon glyphicon-search" })
                        </li>
                       
                      
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                    @{
                        Html.RenderAction("LoginPartial","Home");
                    }
                    </ul>
                </div>
            </div>
        </nav>
    <div class="container body-content">
        @*<p class="marquee">
                <span>New Feature To EPO System.To Modify DueDate For PO,Click on Tools->Modify DueDate.</span>
       
            
        </p>*@
        @*<div class="bs-callout bs-callout-danger bs-callout-notification">
            <span class="glyphicon glyphicon-info-sign"></span>
            \\dnas\ap\ is currently offline! Please don't use Ettacher. We will let you know when it will be available. Thank you for your patience.
            <span class="glyphicon glyphicon-heart"></span>
        </div>*@
        @RenderBody()

        <footer class="col-md-10">
            <hr/>
            <p>&copy; @DateTime.Now.Year - Inguz Harvest Pty Ltd - IT Wacol. Version: @typeof(MvcApplication).Assembly.GetName().Version</p>
        </footer>
    </div>

        @RenderSection("scripts", required: false)
    </body>
</html>

EPOv2/EPOv2/Views/Shared/_PdfLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" href="@Server.MapPath(Url.Content("~/Content/Site.css"))"  />
    <link rel="stylesheet" type="text/css" href="@Server.MapPath(Url.Content("~/Content/bootstrap.css"))" />
    <link rel="stylesheet" href="~/Content/Site.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.css" />
    <title>MvcRazorToPdf</title>
    <style>
        .pdf-supplierbox, .pdf-deliverybox {
            border: 2px black solid;
        }

        .pdf-comment {
            /*border: 1px black solid;*/
            margin-top: 30px;
        }
       

        .pdf-totals {
            border: 1px black solid;
            
        }
        .pdf-totals-numbers {
            text-align: right;
        }

        .pdf-commentHeader.row {
            margin-left: -14px;
        }

        .pdf-approved {
            margin-top: 5px;
        }

        img.pdf-logo {
            height: auto;
            max-width: 300px;
            max-height: 250px;
            text-align: center;
        }

        body {
            font-size: 2.2em;
            padding-top: 0;
            padding-bottom: 10px;
            height: 768px;
            width: 1280px;
        }

        .pdf-header {
            font-size: 1.4em;
        }

        .pdf-smallHeader {
            font-size: 1em;
            font-style: italic;
        }

        .pdf-APE {
            padding-top: 7px;
        }

        .pdf-SupDel-row {
            padding-top: 10px;
        }

        .pdf-supplierbox {
            margin-right: 5px;
        }

        .pdf-deliverybox {
            margin-left: 5px;
            width: 48%;
        }

        .pdf-itemsTable {
            margin-top: 10px;
            /*border: 1px black solid;*/
        }

            .pdf-itemsTable .col-xs-12 {
                padding-left: 0;
            }

        .pdf-orderitems .table-bordered,
        .pdf-orderitems .table-bordered td {
            border: 1px solid #000 !important;
        }

            .pdf-orderitems .table-bordered table {
                border-color: #000;
            }

        .pdf-tableHeaderRow, .pdf-commentHeader, .pdf-approvedHeader, .pdf-termsHeader {
            background-color: #ebeef0;
        }

        .pdf-approvedHeader, .pdf-termsHeader, .pdf-commentHeader {
            border: 1px solid #000;
        }

       

        .line {
            position: absolute;
            top: 1650px;
            border-top: 1px solid #000;
        }
        .pdf-termsHeader {
            padding-left: 300px;
        }
        .breakhere { 
                     display: block;
                clear: both; 
                 page-break-after: always;
        }
        #pdfPage2,#pdfPage3,#pdfPage4,#pdfPage5,#pdfPage6 {
            margin-top: 350px;
        }
        #pdfPage1 .pdf-terms {
            position: absolute;
            top: 1650px;
        }
        #pdfPage2 .pdf-terms {
            position: absolute;
            top: 3540px;
        }
        #pdfPage3 .pdf-terms {
            position: absolute;
            top: 5400px;
        }
        #pdfPage4 .pdf-terms {
            position: absolute;
            top: 7300px;
        }
        #pdfPage5 .pdf-terms {
            position: absolute;
            top: 9150px;
        }
        #pdfPage6 .pdf-terms {
            position: absolute;
            top: 11050px;
        }
    </style>
</head>
<body>
    <div class="col-md-11">
        @RenderBody()
    </div>
</body>
</html>

EPOv2/EPOv2/Views/Shared/_loadingView.cshtml
<div id="divProcessing">
    <div id="loading"><img src="/Content/img/ajax-loader.gif" alt="" /></div>
</div>

EPOv2/EPOv2/Views/Shared/_testPdf.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" href="@Server.MapPath(Url.Content("~/Content/Site.css"))"  />
    <link rel="stylesheet" type="text/css" href="@Server.MapPath(Url.Content("~/Content/bootstrap.css"))" />
    <link rel="stylesheet" href="~/Content/Site.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.css" />
    <title>MvcRazorToPdf</title>
    <style>
        .pdf-supplierbox, .pdf-deliverybox {
            border: 2px black solid;
        }

        .pdf-comment {
            /*border: 1px black solid;*/
            margin-top: 30px;
        }

        .pdf-totals {
            border: 1px black solid;
        }

        .pdf-commentHeader.row {
            margin-left: -14px;
        }

        .pdf-approved {
            margin-top: 5px;
        }

        img.pdf-logo {
            height: auto;
            width: 300px;
        }

        body {
            font-size: 2.2em;
            padding-top: 0;
            padding-bottom: 10px;
            height: 768px;
            width: 1280px;
        }

        .pdf-header {
            font-size: 1.4em;
        }

        .pdf-smallHeader {
            font-size: 1em;
            font-style: italic;
        }

        .pdf-APE {
            padding-top: 7px;
        }

        .pdf-SupDel-row {
            padding-top: 10px;
        }

        .pdf-supplierbox {
            margin-right: 5px;
        }

        .pdf-deliverybox {
            margin-left: 5px;
            width: 48%;
        }

        .pdf-itemsTable {
            margin-top: 10px;
            /*border: 1px black solid;*/
        }

            .pdf-itemsTable .col-xs-12 {
                padding-left: 0;
            }

        .pdf-orderitems .table-bordered,
        .pdf-orderitems .table-bordered td {
            border: 1px solid #000 !important;
        }

            .pdf-orderitems .table-bordered table {
                border-color: #000;
            }

        .pdf-tableHeaderRow, .pdf-commentHeader, .pdf-approvedHeader, .pdf-termsHeader {
            background-color: #ebeef0;
        }

        .pdf-approvedHeader, .pdf-termsHeader, .pdf-commentHeader {
            border: 1px solid #000;
        }

        .pdf-terms {
            position: absolute;
            top: 1650px;
        }

        .line {
            position: absolute;
            top: 1650px;
            border-top: 1px solid #000;
        }
        .pdf-termsHeader {
            padding-left: 300px;
        }
        .breakhere { 
                     display: block;
                clear: both; 
                 page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="col-md-11">
        @RenderBody()
    </div>
</body>
</html>