EPOv2/EPOv2/Controllers/ManageRoutingController.cs
using System.Web.Mvc;

namespace EPOv2.Controllers
{
    public class ManageRoutingController : Controller
    {
       // #region Property

//        //private readonly PurchaseOrderContext _db = new PurchaseOrderContext();
//        private readonly PurchaseOrderOldContext db = new PurchaseOrderOldContext();
///*
//        private readonly cUtilities _cUtil = new cUtilities();
//*/
///*
//        private readonly Directory _adsi = new Directory();
//*/
//        private readonly Routing _routing = new Routing();

//        public PurchaseOrderOldContext Db
//        {
//            get { return this.db; }
//        }

//        public PurchaseOrderOldContext Db1
//        {
//            get { return this.db; }
//        }

//        //code list: 
//        // 7XX -Error
//        //701 - has Cost Centre as owner
//        // 2XX -SUCCESS
//        // 200 - OK

//        #endregion
        
//        // GET: /ManageRouting/AddUser
//        public async Task<ActionResult> AddUser(string result =null, string runtime = null)
//        {
//            var dInfo = new DInfo();
//            dInfo.StartWatch();
//            //var adLst = _routing.GetAllAdUsersName();
//            var usrLst = _routing.GetAllADUsersName();//GetUserLst();
//            var mngLst = await _routing.GetManagerLst();
//            var lvlLst = _routing.GetLevelSelectList();
//            ViewBag.userLst = new SelectList(usrLst);
//            ViewBag.mngLst = new SelectList(mngLst);
//            ViewBag.lvlLst = lvlLst;
//            ViewBag.runtime1 = "DDL runtime: " + dInfo.Stopwatch();
//            ViewBag.runtime2 = "Saveing runtime" + runtime;
//            ViewBag.Result = result;
//            ViewBag.name = _routing.GetADName();

//            return View();
//        }

//        // POST: /ManageRouting/AddUser
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public async Task<ActionResult> AddUser(tblStagingEmployeesDEV stagingEmployee)
//        {
//            if (!ModelState.IsValid) return View();
//            var debugInfo = new DInfo();
//            debugInfo.StartWatch();
//            var sEmployee =
//                this.db.tblStagingEmployeesDEVs.FirstOrDefault(
//                    x => x.Employee == stagingEmployee.Employee && x.Manager == stagingEmployee.Manager);
//            if (sEmployee == null)
//            {
//                this.db.tblStagingEmployeesDEVs.Add(stagingEmployee);
                
//            }
//            else
//            {
//                sEmployee.isDeleted = 0;
//                sEmployee.Level = stagingEmployee.Level;
//            }
            
//            await this.db.SaveChangesAsync();
//            // Add/Update routing
//            _routing.PushRouting(stagingEmployee.Manager,stagingEmployee.Employee, stagingEmployee.Level);
            
//            var elapsedTime = debugInfo.Stopwatch();
//            Debug.WriteLine("KOGOT = AddUser-RunTime: "+elapsedTime);
//            return RedirectToAction("AddUser", "ManageRouting", new { runtime = elapsedTime, result = "Done" });
//        }

//        //public async Task<ActionResult> FlushRouting()
//        //{
//        //    return View();
//        //}
        
//        // GET: /ManageRouting/ManageUsers
//        public async Task<ActionResult> ManageUsers(string code =null)
//        {
//            var empList = await this.db.tblStagingEmployeesDEVs.Where(x => x.isDeleted == 0).OrderBy(x=>x.Employee).ToListAsync();
//            //TODO: make it as Dictionary!!!
//            if (code != null)
//            {
//                if (code.StartsWith("2"))
//                {
//                    ViewBag.Result = "Done";
//                    ViewBag.AlertClass = "alert-success";
//                    ViewBag.Msg = "Done";
//                }
//                else
//                {
//                    ViewBag.Result = "Error";
//                    ViewBag.Msg = "This employee own of Cost Centre, please change owner before deleting";
//                    ViewBag.AlertClass = "alert-danger";
//                }
//            }

//            ViewBag.code = code;
//            return View(empList);
//            //return View();
//        }

//        public async Task<ActionResult> ManageUsersEdit(int? id)
//        {
//            if (id == null) return RedirectToAction("ManageUsers");
//            var emp =this.db.tblStagingEmployeesDEVs.FirstOrDefault(x => x.StagingEmpID == id);
//            var mngLst = await _routing.GetManagerLst();
//            if (emp != null)
//            {
//                var selectedMng = mngLst.Where(x => x.Contains(emp.Manager));
//                ViewBag.mngLst = new SelectList(mngLst, selectedMng);
//                var lvlLst = _routing.GetLevelSelectList(emp.Level);
//                ViewBag.lvlLst = lvlLst;
//            }
//            else
//            {
//                ViewBag.mngLst = new SelectList(mngLst);
//                var lvlLst = _routing.GetLevelSelectList();
//                ViewBag.lvlLst = lvlLst;
//            }
            
//            return PartialView("ManageUsersEdit",emp);
//        }

//        //POST
//        [HttpPost]
//        public async Task<ActionResult> ManageUsersEdit(tblStagingEmployeesDEV stagingEmployee)
//        {
//            if (!ModelState.IsValid) return View();
//            this.db.Entry(stagingEmployee).State = EntityState.Modified;
//            await this.db.SaveChangesAsync();
//            _routing.RemoveNotRelevantRouting(stagingEmployee);
//           _routing.PushRouting(stagingEmployee.Manager, stagingEmployee.Employee, stagingEmployee.Level);
//            return RedirectToAction("ManageUsers");
//        }

//        //GET
//        public async Task<ActionResult> ReplaceManager(string runtime =null,string result=null, string par=null)
//        {
//            var dInfo = new DInfo();
//            dInfo.StartWatch();
            
//            var oldManagerLst = await _routing.GetManagerLst();
//            //var newManagerLst = await _routing.GetManagerLst();
//            ViewBag.oldMngLst = new SelectList(oldManagerLst);
//            ViewBag.newMngLst = new SelectList(oldManagerLst);
//            ViewBag.runtime1 = "DDL runtime: " + dInfo.Stopwatch();
//            ViewBag.runtime2 = "Saveing runtime" + runtime;

//            ViewBag.Result = result;
//            return View();
//        }

//        //POST
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public async Task<ActionResult> ReplaceManager(string oldMng, string newMng)
//        {
//            var dInfo = new DInfo();
//            dInfo.StartWatch();
//            var result = "Done";

//            var oldMngList = this.db.tblStagingEmployeesDEVs.Where(x => x.Manager == oldMng).ToList();
//            foreach (var employee in oldMngList)
//            {
//                this.db.Entry(employee).State = EntityState.Modified;
//                employee.Manager = newMng;
//            }
//            await this.db.SaveChangesAsync();
//            var stagingCostCentre = this.db.tblStagingCostCentresDEVs.FirstOrDefault(x => x.Owner == newMng);
//            if (stagingCostCentre != null) await UpdateCostCentreOwner(stagingCostCentre);
//            else result = "That manager does not own Cost Centre";
//            var elapsedTime = dInfo.Stopwatch(); 
//            return RedirectToAction("ReplaceManager", "ManageRouting", new { runtime = elapsedTime, result });
//        }

//        //GET  /ManageRouting/ChangeOwner
//        public async Task<ActionResult> ChangeOwner(string runtime =null,string result=null, int cc=-1)
//        {
//            var dInfo = new DInfo();
//            dInfo.StartWatch();
//            //if (cc == -1)
//            //{
//                //var usrLst = _routing.GetAllADUsersName();//GetUserLst();
//                var ownerLst = await _routing.GetManagerLst();
//                //var lvlLst = _routing.GetLevelSelectLst(this);
//                //var selectedOwner = 
//                ViewBag.ownerLst = new SelectList(ownerLst);
//                ViewBag.costCentreLst = _routing.GetCostCentreList();

//           // }
//            //else
//            //{
//            //    var selectedCC = _db.tblStagingCostCentresDEVs.FirstOrDefault(x => x.CostCentreCode==cc);
//            //    ViewBag.costCentreLst = _routing.GetCostCentreList(selectedCC);
//            //    var ownerLst = await _routing.GetManagerLst();
//            //    var selectedOwner =
//            //        _db.tblStagingCostCentresDEVs.Where(x => x.StagingCostCentreID == selectedCC.StagingCostCentreID)
//            //            .Select(x => x.Owner).FirstOrDefault();
//            //    ViewBag.ownerLst = new SelectList(ownerLst,selectedOwner);
//            //}
//            ViewBag.runtime1 = "DDL runtime: " + dInfo.Stopwatch();
//            ViewBag.runtime2 = "Saveing runtime" + runtime;
//            ViewBag.Result = result;
            
//            return View();
//        }

//        //Post: /ManageRouting/ChangeOwner
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public async Task<ActionResult> ChangeOwner(tblStagingCostCentresDEV stagingCostCentre)
//        {
//            //if (stagingCostCentre.Owner == null)
//            //  return  RedirectToAction("ChangeOwner", "ManageRouting", new {cc = stagingCostCentre.CostCentreCode});
//            if (!ModelState.IsValid) return View();
//            var debugInfo = new DInfo();
//            var result = "Done";
//            debugInfo.StartWatch();
//            //var e = _routing.GetEmployeeChainList(stagingCostCentre.Owner,Routing.Direction.Up);
//            try
//            {
//                await UpdateCostCentreOwner(stagingCostCentre);
//            }
//            catch (Exception e)
//            {
//                Debug.WriteLine(e.Message);
//                result = e.Message;

EPOv2/EPOv2/Views/ManageRouting/AddUser.cshtml
@*@model DomainModel.Entities.tblStagingEmployeesDEV
    @{
        ViewBag.Title = "AddUser";
    }

    <h2>Add New User</h2>
    @Html.AntiForgeryToken()
    @using (@Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true)
            @{
        if (ViewBag.Result != null)
        {
            <div class="alert alert-success">@ViewBag.Result</div>
        }
    }
            <div class="form-group">
                <div class="form-group">
                    @Html.Label("User: ", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Employee, (SelectList)ViewBag.userLst, "Select user", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Employee)
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Manager: ", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Manager, (SelectList)ViewBag.mngLst, "Select manager", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Manager)
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Level: ", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Level, (SelectList)ViewBag.lvlLst, "Select level", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Level)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" id="btn_adduser" class="btn btn-primary" value="Add user" />
                    </div>
                </div>
            </div>
            @*<div class="alert alert-info">
                @ViewBag.runtime1

                @ViewBag.runtime2

                @ViewBag.Name
            </div>

        </div>
        

}*@

EPOv2/EPOv2/Views/ManageRouting/ChangeOwner.cshtml
@*@model DomainModel.Entities.tblStagingCostCentresDEV
@{
    ViewBag.Title = "Change Cost Centre Owner (OLD)";
}

<h2>Change Cost Centre Owner</h2>
@Html.AntiForgeryToken()
@using (@Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @{
    if (ViewBag.Result != null)
    {
        <div class="alert alert-success">@ViewBag.Result</div>
    }
        }
        <div class="form-group">
            <div class="form-group">
                @Html.Label("Cost Centre: ", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CostCentreCode, (SelectList)ViewBag.costCentreLst, "Select Cost Centre", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CostCentreCode)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Owner: ", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Owner, (SelectList)ViewBag.ownerLst, "Select Owner", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Owner)
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" id="btn_updateCCOwner" class="btn btn-primary" value="Update" />
                </div>
            </div>
        </div>
        @*<div class="alert alert-info">
            @ViewBag.runtime1

            @ViewBag.runtime2

            @ViewBag.Name
        </div>

    </div>


}*@

EPOv2/EPOv2/Views/ManageRouting/Create.cshtml
@*@model DomainModel.Entities.tblStagingAccCC

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblStagingAccCC</h4>
        <hr />
        @Html.ValidationSummary(true)

    <div class="form-group">
        <div class="form-group">
            @Html.LabelFor(model => model.AccountCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountCode)
                @Html.ValidationMessageFor(model => model.AccountCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StagingCostCentreID, "StagingCostCentreID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StagingCostCentreID", String.Empty)
                @Html.ValidationMessageFor(model => model.StagingCostCentreID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDeleted, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isDeleted)
                @Html.ValidationMessageFor(model => model.isDeleted)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created)
                @Html.ValidationMessageFor(model => model.Created)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Updated, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Updated)
                @Html.ValidationMessageFor(model => model.Updated)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

EPOv2/EPOv2/Views/ManageRouting/Delete.cshtml
@*@model DomainModel.Entities.tblStagingAccCC

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblStagingAccCC</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tblStagingCostCentresDEV.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblStagingCostCentresDEV.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@

EPOv2/EPOv2/Views/ManageRouting/Details.cshtml
@*@model DomainModel.Entities.tblStagingAccCC

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tblStagingAccCC</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tblStagingCostCentresDEV.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblStagingCostCentresDEV.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StagingAccCCID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

EPOv2/EPOv2/Views/ManageRouting/Edit.cshtml
@*@model DomainModel.Entities.tblStagingAccCC

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblStagingAccCC</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.StagingAccCCID)

        <div class="form-group">
            @Html.LabelFor(model => model.AccountCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountCode)
                @Html.ValidationMessageFor(model => model.AccountCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StagingCostCentreID, "StagingCostCentreID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StagingCostCentreID", String.Empty)
                @Html.ValidationMessageFor(model => model.StagingCostCentreID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDeleted, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isDeleted)
                @Html.ValidationMessageFor(model => model.isDeleted)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created)
                @Html.ValidationMessageFor(model => model.Created)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Updated, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Updated)
                @Html.ValidationMessageFor(model => model.Updated)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

EPOv2/EPOv2/Views/ManageRouting/FlushRouting.cshtml
@{
    ViewBag.Title = "FlushRouting";
}

<h2>FlushRouting</h2>

EPOv2/EPOv2/Views/ManageRouting/Index.cshtml
@*@model IEnumerable<DomainModel.Entities.tblStagingAccCC>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.tblStagingCostCentresDEV.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isDeleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Updated)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.tblStagingCostCentresDEV.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccountCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isDeleted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Updated)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.StagingAccCCID }) |
            @Html.ActionLink("Details", "Details", new { id=item.StagingAccCCID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.StagingAccCCID })
        </td>
    </tr>
}

</table>*@

EPOv2/EPOv2/Views/ManageRouting/ManageUsers.cshtml
@*@model IEnumerable<DomainModel.Entities.tblStagingEmployeesDEV>
@{
    ViewBag.Title = "Manage Users";
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#divProcessing").hide();

        $('#my-dialog').dialog({
            title: 'Edit Customer',
            autoOpen: false,
            resizable: false,
            height: 350,
            width: 450,
            show: {
                effect: 'fadeIn'
            },
            modal: true,
            draggable: true,
            open: function (event, ui) {
                $(this).load(url);

            },
            close: function (event, ui) {
                $(this).dialog('close');
            }

        });

        $('.modalDialog').click(function () {
            $('#my-dialog').load(this.href, function () {
                $(this).dialog('open');
            });
            return false;
        });
    });
</script>


<h2>ManageUsers</h2>

@{
    if (ViewBag.code != null)
    {
        <div class="alert @ViewBag.AlertClass">@ViewBag.Msg</div>
    }
}

<div id="my-dialog"></div>
<div class="col-md-7">
    <table class="table table-striped table-condensed ">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Employee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Level)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manager)
            </th>
            <th></th>
        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Level)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Manager)
                </td>
                <td>
                    @Html.ActionLink("Edit", "ManageUsersEdit", new { id = item.StagingEmpID }, new { @class = "modalDialog" })

                    @Html.ActionLink("Delete", "DeleteManageUser", new { id = item.StagingEmpID }, new {onclick="return confirm('Are you sure you want to delete "+@Html.DisplayFor(modelItem=>item.Employee) +"?')"})
                </td>
            </tr>
        }

    </table>
</div>*@

EPOv2/EPOv2/Views/ManageRouting/ManageUsersEdit.cshtml
@*@model DomainModel.Entities.tblStagingEmployeesDEV
<script>
    $(function () {
        $("#loading").hide();

        $(".ui-dialog")
                .find(".ui-dialog-titlebar").remove();

        $("#saveManageUser").click(function () {
            //  $("#my-dialog").dialog("close");
            $("#manageUserEdit").hide();

            $(".ui-dialog")
                .css("border", "0 none")
                .css("background", "transparent")
                .find(".ui-dialog-titlebar").remove();
            $("#loading").show();
            // Hide the "busy" Gif at load:
        });
    });
</script>

<div id="loading"><img src="~/Content/img/ajax-loader.gif" alt="" /></div>
@using (Html.BeginForm("ManageUsersEdit", "ManageRouting", FormMethod.Post, new { enctype = "multipart/form-data", id = "manageUserEdit", name = "Edit User" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>Change Employee</h3>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.StagingEmpID)
        @Html.HiddenFor(model => model.Employee)

        <div class="form-group">
            @Html.Label("Employee: ", new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                     <i>@Html.DisplayFor(model => model.Employee, new { @class = "form-control" })</i>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Manager: ", new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownListFor(model => model.Manager, (SelectList)ViewBag.mngLst, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Manager)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Level: ", new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownListFor(model => model.Level, (SelectList)ViewBag.lvlLst, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Level)
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" id="saveManageUser" />
                <button type="button" class="btn btn-default" onclick="$('#my-dialog').dialog('close');">Close</button>
            </div>
        </div>
    </div>
}*@